- name: change route53
  route53:
    state: present
    zone: cardozo.dev
    record: www.cardozo.dev
    failover: PRIMARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ NEW_ALIAS }}"
    wait: yes
    health_check: "c838c25b-589b-4a15-8b9e-7bfdc5665959"
